#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 13 10:02:22 2023

@author: epoirier1
"""

import pandas as pd
from matplotlib import pyplot
from datetime import date, time, datetime

# ************************************************************************************
# This code is to read a raw Cat.txt downloaded from a PME MiniDOT logger

# path to the concatenated file Cat.txt on your machine
path = '/home/path.to/my/Cat.txt'

# df is a dataframe created with all the file columns
# careful for value header=row. The file row counts starts at row 0
df = pd.read_csv(path, header=2, delimiter=',', index_col=0)

# convert the index times from unix seconds to date time AAAA-MM-DD HH:MM:SS
df.index = pd.to_datetime(df.index, unit='s')

# plot the column number you want to see (number of first column is 0)
df.plot(y=df.columns[1], style='.-', markevery=5)

# show the first lines of the df dataframe
print(df.head())
# show the last lines of the df dataframe
print(df.tail())
# show the basic statistics of all columns of the dataframe
print(df.describe())

# ****************************************************************************

# This code is to select a dfs of data of interest

# ****************************************************************************
# Specify your the start and end time of that data you are interested in
start = datetime(2023,5,23,7,50,00)
end = datetime(2023,5,23,8,40,00)

# this shorten the df dataframe into a smaller one called dfs
# containig the data of interest
dfs = df[start_palier1 : end_palier1]
dfs.plot(y=dfs.columns[2], style='.-', markevery=5)
